name: ChestShop-towny

main: com.acrobot.chestshop.towny.Towny
version: '${project.bukkitPluginVersion}'
api-version: ${project.bukkitAPIVersion}

author: Acrobot
description: A towny integration for ChestShop 
 
depend: [ChestShop, Towny]

permissions:
  ChestShop.towny.bypass:
    default: op
  ChestShop.towny.create.townshop:
    default: op
    children:
      ChestShop.towny.create.townshop.buy: true
      ChestShop.towny.create.townshop.sell: true
  ChestShop.towny.create.nationshop:
    default: op
    children:
      ChestShop.towny.create.nationshop.buy: true
      ChestShop.towny.create.nationshop.sell: true